name: PyPI Tests

# We don't want pushes (or PRs) to gh-pages to kick anything off
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  PyPITests:
    name: ${{ matrix.python-version }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    # We check out only a limited depth and then pull tags to save time
    - name: Checkout source
      uses: actions/checkout@v2
      with:
        fetch-depth: 100

    - name: Get tags
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
